export const FETCH_NOTES_REQUEST = 'FETCH_NOTES_REQUEST';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const FETCH_NOTES_FAILURE = 'FETCH_NOTES_FAILURE';

export const CREATE_NOTE_REQUEST = 'CREATE_NOTE_REQUEST';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const CREATE_NOTE_FAILURE = 'CREATE_NOTE_FAILURE';

export const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';

export const ARCHIVE_NOTE_REQUEST = 'ARCHIVE_NOTE_REQUEST';
export const ARCHIVE_NOTE_SUCCESS = 'ARCHIVE_NOTE_SUCCESS';
export const ARCHIVE_NOTE_FAILURE = 'ARCHIVE_NOTE_FAILURE';

export const UNARCHIVE_NOTE_REQUEST = 'UNARCHIVE_NOTE_REQUEST';
export const UNARCHIVE_NOTE_SUCCESS = 'UNARCHIVE_NOTE_SUCCESS';
export const UNARCHIVE_NOTE_FAILURE = 'UNARCHIVE_NOTE_FAILURE';
